apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm

resources:
  - ns.yaml
  - deployment.yaml
  - vllm-server-svc.yaml
  - secrets.yaml
  - vllm-server-pvc.yaml
  - vllm-build-job.yaml
