apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-access-token
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-access-token"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vllm-model
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/vllm-model"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-secret
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-config"
type: kubernetes.io/dockerconfigjson
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-pat
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/github-pat"
