apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: huggingface-token
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/huggingface-token"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vllm-model
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/vllm-model"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-secret
  namespace: vllm
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-config"
type: kubernetes.io/dockerconfigjson
