apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-server-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: no-replicas
  volumeMode: Filesystem
