apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: data-warehouse-owner
  namespace: cnpg-dev
  labels:
    cnpg.io/reload: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/data-warehouse-owner"
type: kubernetes.io/basic-auth
