apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - infra-cluster.yaml
  - aws-s3-creds.yaml
  - scheduled-backup-infra.yaml
  - role-secrets.yaml
  - s3-store.yaml
