apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: typesense

helmCharts:
  - name: typesense-operator
    repo: https://akyriako.github.io/typesense-operator/
    version: 0.3.6
    releaseName: typesense-operator
    namespace: typesense
    includeCRDs: true

resources:
  - typesense-api-key.yaml
  - ns.yaml
  - external-route.yaml
  - internal-route.yaml
  - typesense-cluster.yaml
