apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: typesense/typesense:29.0
  replicas: 3
  storage:
    size: 10Gi
    storageClassName: no-replicas
  enableCors: true
  corsDomains: "https://gearhawk.io"
  adminApiKey:
    name: typesense-api-key
  resources:
    requests:
      cpu: 2

    limits:
      memory: 8Gi
      cpu: 6
