apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  image: typesense/typesense:29.0
  replicas: 1
  storage:
    size: 1Gi
    storageClassName: no-replicas
  enableCors: false
  adminApiKey:
    name: typesense-api-key
  resources:
    limits:
      memory: 4Gi
      cpu: 4
