grpc:
  replicaCount: 3
  envFrom:
    - secretRef:
        name: hatchet-config
controllers:
  replicaCount: 2
  envFrom:
    - secretRef:
        name: hatchet-config
scheduler:
  replicaCount: 2
  envFrom:
    - secretRef:
        name: hatchet-config
sharedConfig:
  # you can disable shared config by setting this to false
  enabled: true
  # you can set additional environment variables here, which will override any defaults
  envFrom:
    - secretRef:
        name: hatchet-config
postgres:
  enabled: false
rabbitmq:
  enabled: false
api:
  envFrom:
    - secretRef:
        name: hatchet-config

frontend:
  resources:
    limits:
      memory: 4096Mi
