apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-worker
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-worker
  template:
    metadata:
      labels:
        app: image-worker
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: image-worker
          image: wjt40398/gearhawk:image-worker-66cd135

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 90
            periodSeconds: 10

          env:
            - name: NODE_ENV
              value: "production"

            - name: WORKER_CONCURRENCY
              value: "40"

            # OTEL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=data-pipeline,deployment.environment=production"

            # Hatchet
            - name: HATCHET_CLIENT_HOST_PORT
              value: "hatchet-grpc.hatchet.svc.cluster.local:7070"
            - name: HATCHET_CLIENT_WORKER_HEALTHCHECK_ENABLED
              value: "True"
            - name: HATCHET_CLIENT_TLS_STRATEGY
              value: "none"
            - name: HATCHET_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: HATCHET_CLIENT_TOKEN

            # Credentials
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: DB_URL

            - name: R2_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: R2_ENDPOINT
            - name: R2_PUBLIC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: R2_PUBLIC_ENDPOINT
            - name: R2_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: R2_BUCKET_NAME

            - name: R2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: R2_ACCESS_KEY_ID
            - name: R2_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pipeline-worker-secrets
                  key: R2_SECRET_ACCESS_KEY
