apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-secret
  namespace: pipeline-workers
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-config"
type: kubernetes.io/dockerconfigjson
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pipeline-worker-secrets
  namespace: pipeline-workers
spec:
  itemPath: "vaults/gearhawk-k8s/items/pipeline-worker-secrets"
