apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hatchet-pg-cluster
  namespace: cnpg-hatchet
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  imagePullPolicy: IfNotPresent
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    # TODO: performance tuning https://www.enterprisedb.com/postgres-tutorials/introduction-postgresql-performance-tuning-and-optimization?lang=en
    # using: https://pgtune.leopard.in.ua/
    # WARNING: WAL tuning parameters should be the same as the backups

    # additional tunning for hatchet db's https://docs.hatchet.run/self-hosting/improving-performance
    parameters:
      timezone: "Etc/UTC"
      max_connections: "1500"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1390kB"
      huge_pages: "off"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      max_parallel_maintenance_workers: "4"

  bootstrap:
    # initdb:
    #   database: hatchet
    #   owner: hatchet
    #   secret:
    #     name: hatchet-user
    recovery:
      source: s3
      database: hatchet
      owner: hatchet
      secret:
        name: gearhawk-postgres-app

  enableSuperuserAccess: true
  superuserSecret:
    name: gearhawk-postgres-superuser

  storage:
    # TODO: benchmark and use local storage
    storageClass: no-replicas
    size: 15Gi

  externalClusters:
    - name: s3
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          # Recovery Object Store (pull, read-only)
          barmanObjectName: s3-store
          serverName: recovery-target-cnpg-hatchet # the target path where base + wal objects are stored
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        # Backup Object Store (push, read-write)
        barmanObjectName: s3-store
        serverName: scheduled-backup-cnpg-hatchet # this s3 path must be empty during recovery

  resources:
    requests:
      memory: "8Gi"
      cpu: "2"
    limits:
      memory: "12Gi"
      cpu: "8"
  monitoring:
    enablePodMonitor: false

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
