apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - hatchet-cluster.yaml
  - pooler-rw.yaml
  - role-secrets.yaml
  - aws-s3-creds.yaml
  - scheduled-backup.yaml
  - s3-store.yaml
